version: "2.2"

networks:
  net4-45:
    ipam:
      config:
        - subnet: 172.21.45.0/24

  net4-46:
    ipam:
      config:
        - subnet: 172.21.46.0/24

  net4-47:
    ipam:
      config:
        - subnet: 172.21.47.0/24

services:
  Router1:
    image: rprustagi/amd64-router
    container_name: R1
    privileged: true
    tty: true
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.ip_no_pmtu_disc=1
    cap_add:
      - ALL
    networks:
      net4-45:
        ipv4_address: 172.21.45.254
      net4-46:
        ipv4_address: 172.21.46.253
    command: bash -c "
                      mkdir -p /tmp
                      && hostname R1
                      && ip route delete default
                      && ip route add default via 172.21.46.254
                      && ip link set dev eth0 mtu 1200
                      && ip link set dev eth1 mtu 1200
                      && tail -f /dev/null
                     "

  Router2:
    image: rprustagi/amd64-router
    container_name: R2
    privileged: true
    tty: true
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.ip_no_pmtu_disc=1
    cap_add:
      - ALL
    networks:
      net4-46:
        ipv4_address: 172.21.46.254
      net4-47:
        ipv4_address: 172.21.47.254
    command: bash -c "
                      mkdir -p /tmp
                      && hostname R2
                      && ip route delete default
                      && ip route add default via 172.21.46.253
                      && ip link set dev eth0 mtu 800
                      && ip link set dev eth1 mtu 800
                      && tail -f /dev/null
                     "

  Host1:
    image: rprustagi/amd64-ub22-host
    container_name: HA
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      net4-45:
        ipv4_address: 172.21.45.5
    command: bash -c "
                      mkdir -p /tmp
                      && hostname HA
                      && ip route delete default
                      && ip route add default via 172.21.45.254
                      && tail -f /dev/null
                     "

  Host2:
    image: rprustagi/amd64-ub22-host
    container_name: HB
    privileged: true
    ports:
      - "80:80"
      - "2222:22"
    tty: true
    cap_add:
      - ALL
    networks:
      net4-47:
        ipv4_address: 172.21.47.5
    command: bash -c "
                      mkdir -p /tmp
                      && hostname HB
                      && ip route delete default
                      && ip route add default via 172.21.47.254
                      && ip link set dev eth0 mtu 800
                      && tail -f /dev/null
                     "

