version: "3"

networks:
  net-1_24:
    ipam:
      config:
        - subnet: 172.21.1.0/24

  net-2_24:
    ipam:
      config:
        - subnet: 172.21.2.0/24

  net-3_24:
    ipam:
      config:
        - subnet: 172.21.3.0/24

  net-4_24:
    ipam:
      config:
        - subnet: 172.21.4.0/24

  net-5_24:
    ipam:
      config:
        - subnet: 172.21.5.0/24

  net-6_24:
    ipam:
      config:
        - subnet: 172.21.6.0/24

services:
  R1:
    image: rprustagi/amd64-router
    container_name: R1
    privileged: true
    tty: true
    cap_add:
        - ALL
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    networks:
      net-1_24:
        ipv4_address: 172.21.1.254
      net-2_24:
        ipv4_address: 172.21.2.253
      net-4_24:
        ipv4_address: 172.21.4.254
    command: bash -c "ip route delete default
                      && ip route add default via 172.21.2.254
                      && tail -f /dev/null
                     "

  R2:
    image: rprustagi/amd64-router
    container_name: R2
    privileged: true
    tty: true
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    cap_add:
      - ALL
    networks:
      net-2_24:
        ipv4_address: 172.21.2.254
      net-3_24:
        ipv4_address: 172.21.3.253
      net-5_24:
        ipv4_address: 172.21.5.254
    command: bash -c "ip route delete default
                      && ip route add default via 172.21.3.254
                      && tail -f /dev/null
                     "

  R3:
    image: rprustagi/amd64-router
    container_name: R3
    privileged: true
    tty: true
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    cap_add:
      - ALL
    networks:
      net-1_24:
        ipv4_address: 172.21.1.253
      net-3_24:
        ipv4_address: 172.21.3.254
      net-6_24:
        ipv4_address: 172.21.6.254
    command: bash -c "ip route delete default
                      && ip route add default via 172.21.1.254
                      && tail -f /dev/null
                     "

  HA:
    image: rprustagi/amd64-ub22-host
    container_name: HA
    privileged: true
    tty: true
    cap_add:
        - ALL
    networks:
      net-4_24:
        ipv4_address: 172.21.4.5
    command: bash -c "ip route delete default
                      && ip route add default via 172.21.4.254
                      && tail -f /dev/null
                     "

  HB:
    image: rprustagi/amd64-ub22-host
    container_name: HB
    privileged: true
    tty: true
    cap_add:
        - ALL
    networks:
      net-5_24:
        ipv4_address: 172.21.5.5
    command: bash -c "ip route delete default
                      && ip route add default via 172.21.5.254
                      && tail -f /dev/null
                     "

  HC:
    image: rprustagi/amd64-ub22-host
    container_name: HC
    privileged: true
    tty: true
    cap_add:
        - ALL
    networks:
      net-6_24:
        ipv4_address: 172.21.6.5
    command: bash -c "ip route delete default
                      && ip route add default via 172.21.6.254
                      && tail -f /dev/null
                     "
