#version: "3"

networks:
  net4-4:
    ipam:
      config:
        - subnet: 172.21.4.0/24

  net4-3:
    ipam:
      config:
        - subnet: 172.21.3.0/24

  net4-2:
    ipam:
      config:
        - subnet: 172.21.2.0/24

  net4-5:
    ipam:
      config:
        - subnet: 172.21.5.0/24

services:
  Router1:
    image: rprustagi/amd64-router
    container_name: R1
    privileged: true
    tty: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - ALL
    networks:
      net4-4:
        ipv4_address: 172.21.4.254
      net4-2:
        ipv4_address: 172.21.2.254
      net4-3:
        ipv4_address: 172.21.3.254
    command: bash -c "
                      mkdir -p /tmp
                      && ip route delete default
                      && ip route add default via 172.21.2.253
                      && tail -f /dev/null
                     "

  Router2:
    image: rprustagi/amd64-router
    container_name: R2
    privileged: true
    tty: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - ALL
    networks:
      net4-2:
        ipv4_address: 172.21.2.253
      net4-5:
        ipv4_address: 172.21.5.254
    command: bash -c "
                      mkdir -p /tmp
                      && ip route delete default
                      && ip route add default via 172.21.2.254
                      && tail -f /dev/null
                     "

  Host1:
    image: rprustagi/amd64-ub22-host
    container_name: HA
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      net4-4:
        ipv4_address: 172.21.4.5
    command: bash -c "
                      mkdir -p /tmp
                      && ip route delete default
                      && ip route add default via 172.21.4.254
                      && tail -f /dev/null
                     "

  Host2:
    image: rprustagi/amd64-ub22-host
    container_name: HB
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      net4-3:
        ipv4_address: 172.21.3.5
    command: bash -c "
                      mkdir -p /tmp
                      && ip route delete default
                      && ip route add default via 172.21.3.254
                      && tail -f /dev/null
                     "


  Host3:
    image: rprustagi/amd64-ub22-host
    container_name: HC
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      net4-5:
        ipv4_address: 172.21.5.5
    command: bash -c "
                      mkdir -p /tmp
                      && ip route delete default
                      && ip route add default via 172.21.5.254
                      && tail -f /dev/null
                     "
