version: "3.0"

networks:
  net4-net:
    ipam:
      config:
        - subnet: 93.184.214.0/24

  net4-home:
    ipam:
      config:
        - subnet: 172.21.4.0/24

  net4-work:
    ipam:
      config:
        - subnet: 192.168.3.0/24

services:
  Gateway:
    image: rprustagi/amd64-router
    container_name: GW
    tty: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - ALL
    networks:
      net4-net:
        ipv4_address: 93.184.214.254
      net4-home:
        ipv4_address: 172.21.4.253
    command: bash -c "
                      mkdir -p /tmp
                      && hostname GW
                      && ip route delete default
                      && ip route add default via 93.184.214.14
                      && ip route add 192.168.3.0/24 via 172.21.4.254
                      && tail -f /dev/null
                     "
  Firewall:
    image: rprustagi/amd64-router
    container_name: FW
    tty: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - ALL
    devices:
       - "/dev/net/tun:/dev/net/tun"
    networks:
      net4-home:
        ipv4_address: 172.21.4.254
      net4-work:
        ipv4_address: 192.168.3.254
    command: bash -c "
                      mkdir -p /tmp
                      && hostname FW
                      && ip route delete default
                      && ip route add default via 172.21.4.253
                      && tail -f /dev/null
                     "

  Internet:
    image: rprustagi/amd64-ub22-vpn
    container_name: Net
    tty: true
    sysctls:
      - net.ipv4.ip_forward=0
    cap_add:
      - ALL
    networks:
      net4-net:
        ipv4_address: 93.184.214.14
    command: bash -c "
                      mkdir -p /tmp
                      && hostname Net
                      && ip route add 172.21.4.0/24 via 93.184.214.254
                      && ip route add 192.168.3.0/24 via 93.184.214.254
                      && service ssh start
                      && apache2ctl start
                      && tail -f /dev/null
                     "
  Home1:
    image: rprustagi/amd64-ub22-vpn
    container_name: H1
    tty: true
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - ALL
    devices:
       - "/dev/net/tun:/dev/net/tun"
    networks:
      net4-home:
        ipv4_address: 172.21.4.5
    command: bash -c "
                      mkdir -p /tmp
                      && hostname H1
                      && ip route delete default
                      && ip route add default via 172.21.4.253
                      && ip route add 192.168.3.0/24 via 172.21.4.254
                      && service ssh start
                      && apache2ctl start
                      && tail -f /dev/null
                     "

  Home2:
    image: rprustagi/amd64-ub22-vpn
    container_name: H2
    tty: true
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=0
    cap_add:
      - ALL
    devices:
       - "/dev/net/tun:/dev/net/tun"
    networks:
      net4-home:
        ipv4_address: 172.21.4.6
    command: bash -c "
                      mkdir -p /tmp
                      && hostname H2
                      && ip route delete default
                      && ip route add default via 172.21.4.253
                      && ip route add 192.168.3.0/24 via 172.21.4.254
                      && service ssh start
                      && apache2ctl start
                      && tail -f /dev/null
                     "

  Home3:
    image: rprustagi/amd64-ub22-vpn
    container_name: H3
    tty: true
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=0
    cap_add:
      - ALL
    devices:
       - "/dev/net/tun:/dev/net/tun"
    networks:
      net4-home:
        ipv4_address: 172.21.4.7
    command: bash -c "
                      mkdir -p /tmp
                      && hostname H3
                      && ip route delete default
                      && ip route add default via 172.21.4.253
                      && ip route add 192.168.3.0/24 via 172.21.4.254
                      && service ssh start
                      && apache2ctl start
                      && tail -f /dev/null
                     "

  Server1:
    image: rprustagi/amd64-ub22-vpn
    container_name: S1
    tty: true
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - ALL
    devices:
       - "/dev/net/tun:/dev/net/tun"
    networks:
      net4-work:
        ipv4_address: 192.168.3.5
    command: bash -c "
                      mkdir -p /tmp
                      && hostname S1
                      && ip route delete default
                      && ip route add default via 192.168.3.254
                      && service ssh start
                      && apache2ctl start
                      && tail -f /dev/null
                     "

  Server2:
    image: rprustagi/amd64-ub22-vpn
    container_name: S2
    tty: true
    privileged: true
    cap_add:
      - ALL
    devices:
       - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv4.ip_forward=0
    networks:
      net4-work:
        ipv4_address: 192.168.3.6
    command: bash -c "
                      mkdir -p /tmp
                      && hostname S2
                      && ip route delete default
                      && ip route add default via 192.168.3.254
                      && service ssh start
                      && apache2ctl start
                      && tail -f /dev/null
                     "

  Server3:
    image: rprustagi/amd64-ub22-vpn
    container_name: S3
    tty: true
    privileged: true
    cap_add:
      - ALL
    devices:
       - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv4.ip_forward=0
    networks:
      net4-work:
        ipv4_address: 192.168.3.7
    command: bash -c "
                      mkdir -p /tmp
                      && hostname S3
                      && ip route delete default
                      && ip route add default via 192.168.3.254
                      && service ssh start
                      && apache2ctl start
                      && tail -f /dev/null
                     "

