version: "3"

networks:
  net4-0:
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  Host1:
    image: rprustagi/arm64-ub22-host
    container_name: H1
    privileged: true
    tty: true
    cap_add:
        - ALL
    networks:
      net4-0:
        ipv4_address: 172.21.0.11
    command: bash -c " 
                       mkdir -p /tmp
                       && tail -f /dev/null "

#                       && ip route delete default

  Host2:
    image: rprustagi/arm64-ub22-host
    container_name: H2
    privileged: true
    tty: true
    cap_add:
        - ALL
    networks:
      net4-0:
        ipv4_address: 172.21.0.12
    command: bash -c " 
                       mkdir -p /tmp
                       && tail -f /dev/null "


  Host3:
    image: rprustagi/arm64-ub22-host
    container_name: H3
    privileged: true
    tty: true
    cap_add:
        - ALL
    networks:
      net4-0:
        ipv4_address: 172.21.0.13
    command: bash -c " 
                       mkdir -p /tmp
                       && tail -f /dev/null "

  Host4:
    image: rprustagi/arm64-ub22-host
    container_name: H4
    privileged: true
    tty: true
    cap_add:
        - ALL
    networks:
      net4-0:
        ipv4_address: 172.21.0.14
    command: bash -c " 
                       mkdir -p /tmp
                       && tail -f /dev/null "

