version: "2.2"

networks:
  net4-45:
    ipam:
      config:
        - subnet: 172.21.45.0/24

  net4-46:
    ipam:
      config:
        - subnet: 172.21.46.0/24

  net4-47:
    ipam:
      config:
        - subnet: 172.21.47.0/24

services:
  Router1:
    image: rprustagi/arm64-ub22-host
    container_name: R1
    privileged: true
    tty: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - ALL
    networks:
      net4-45:
        ipv4_address: 172.21.45.254
      net4-46:
        ipv4_address: 172.21.46.253
    command: bash -c "
                      mkdir -p /tmp
                      && ip route delete default
                      && ip route add default via 172.21.46.254
                      && tail -f /dev/null
                     "

  Router2:
    image: rprustagi/arm64-ub22-host
    container_name: R2
    privileged: true
    tty: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - ALL
    networks:
      net4-46:
        ipv4_address: 172.21.46.254
      net4-47:
        ipv4_address: 172.21.47.254
    command: bash -c "
                      mkdir -p /tmp
                      && ip route delete default
                      && ip route add default via 172.21.46.253
                      && tail -f /dev/null
                     "

  Host1:
    image: rprustagi/arm64-ub22-host
    container_name: HA
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      net4-45:
        ipv4_address: 172.21.45.5
    command: bash -c "
                      mkdir -p /tmp
                      && ip route delete default
                      && ip route add default via 172.21.45.254
                      && tail -f /dev/null
                     "

  Host3:
    image: rprustagi/arm64-ub22-host
    container_name: HC
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      net4-45:
        ipv4_address: 172.21.45.7
    command: bash -c "
                      mkdir -p /tmp
                      && ip route delete default
                      && ip route add default via 172.21.45.254
                      && tail -f /dev/null
                     "
  Host2:
    image: rprustagi/arm64-ub22-host
    container_name: HB
    privileged: true
    ports:
      - "80:80"
      - "2222:22"
    tty: true
    cap_add:
      - ALL
    networks:
      net4-47:
        ipv4_address: 172.21.47.5
    command: bash -c "
                      mkdir -p /tmp
                      && ip route delete default
                      && ip route add default via 172.21.47.254
                      && tail -f /dev/null
                     "

  Host4:
    image: rprustagi/arm64-ub22-host
    container_name: HD
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      net4-47:
        ipv4_address: 172.21.47.7
    command: bash -c "
                      mkdir -p /tmp
                      && ip route delete default
                      && ip route add default via 172.21.47.254
                      && tail -f /dev/null
                     "

