version: "3"

networks:
  net-int:
    ipam:
      config:
        - subnet: 172.21.1.0/24
  net-lan:
    ipam:
      config:
        - subnet: 172.21.2.0/24

services:
  web:
    image: rprustagi/arm64-ub22-host
    hostname: web
    networks:
      net-lan:
    expose: 
      - "80"
    command: bash -c "apachectl start 
                     && tail -f /dev/null
                     "

  Loadbalancer:
    image: rprustagi/arm64-nginx-lb
    networks:
      net-lan:
        ipv4_address: 172.21.2.254
      net-int:
        ipv4_address: 172.21.1.254
    volumes:
      - ./nginx_lb_web.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "80:80"
    command: bash -c "nginx 
                     && tail -f /dev/null
                     "

