services:
  Router1:
    build:
      context: ../df
      dockerfile: ubuntu-router.df
      target: ubuntu-router
    image: umbc/csee/cns/ubuntu-router
    container_name: R1N64
    hostname: R1N64
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv6.conf.all.forwarding: "1"
    networks:
      net64-1:
        ipv4_address: 172.21.1.254
        ipv6_address: fd00:1001::254
      net64-2:
        ipv4_address: 172.21.2.254
        ipv6_address: fd00:1002::254
    command: >
      bash -c " 
      mkdir -p /tmp
      && ip route del default
      && ip -6 route del default
      && ip route add default via 172.21.2.253 
      && ip -6 route add default via fd00:1002::253
      && tail -f /dev/null 
      "

  Router2:
    build:
      context: ../df
      dockerfile: ubuntu-router.df
      target: ubuntu-router
    image: umbc/csee/cns/ubuntu-router
    container_name: R2N64
    hostname: R2N64
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv6.conf.all.forwarding: "1"
    networks:
      net64-2:
        ipv4_address: 172.21.2.253
        ipv6_address: fd00:1002::253
      net64-3:
        ipv4_address: 172.21.3.253
        ipv6_address: fd00:1003::253
    command: >
      bash -c " 
      mkdir -p /tmp
      && ip route del default
      && ip -6 route del default
      && ip route add default via 172.21.2.254 
      && ip -6 route add default via fd00:1002::254
      && tail -f /dev/null 
      "

  Host1:
    build:
      context: ../df
      dockerfile: ubuntu-host.df
      target: ubuntu-host
    image: umbc/csee/cns/ubuntu-host
    container_name: H1N64
    hostname: H1N64
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      net64-1:
        ipv4_address: 172.21.1.5
        ipv6_address: fd00:1001::5
    ports:
      - "8081:80"
    command: >
      bash -c " 
      mkdir -p /tmp
      && ip route del default
      && ip -6 route del default
      && service apache2 start 
      && ip route add default via 172.21.1.254 
      && ip -6 route add default via fd00:1001::254
      && tail -f /dev/null 
      "

  Host2:
    build:
      context: ../df
      dockerfile: ubuntu-host.df
      target: ubuntu-host
    image: umbc/csee/cns/ubuntu-host
    container_name: H2N64
    hostname: H2N64
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      net64-3:
        ipv4_address: 172.21.3.5
        ipv6_address: fd00:1003::5
    ports:
      - "8082:80"
    command: >
      bash -c " 
      mkdir -p /tmp
      && ip route del default
      && ip -6 route del default
      && service apache2 start 
      && ip route add default via 172.21.3.253 
      && ip -6 route add default via fd00:1003::253
      && tail -f /dev/null 
      "

networks:
  net64-1:
    name: net64-1
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.21.1.0/24
        - subnet: fd00:1001::/64

  net64-2:
    name: net64-2
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.21.2.0/24
        - subnet: fd00:1002::/64

  net64-3:
    name: net64-3
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.21.3.0/24
        - subnet: fd00:1003::/64
