services:
  db:
    image: mariadb:11
    container_name: moodle-db
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: moodle
      MARIADB_USER: moodle
      MARIADB_PASSWORD: moodlepass
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  moodle:
    image: erseco/alpine-moodle:latest
    container_name: moodle
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SITE_URL: http://localhost:8080
      DB_TYPE: mariadb
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: moodle
      DB_USER: moodle
      DB_PASS: moodlepass

      MOODLE_SITENAME: "QTI-Converter-Moodle"
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: admin123
      MOODLE_EMAIL: admin@example.com
    volumes:
      - moodledata:/var/www/moodledata
      - moodlehtml:/var/www/html
    restart: unless-stopped

volumes:
  mariadb_data:
  moodledata:
  moodlehtml:

