[libdefaults]
    default_realm = CSEE.UMBC.TEST
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false
    ticket_lifetime = 24h
    forwardable = true

[realms]
    CSEE.UMBC.TEST = {
        kdc = kdc.csee.umbc.test
        admin_server = kdc.csee.umbc.test
    }

[domain_realm]
    .csee.umbc.test = CSEE.UMBC.TEST
    csee.umbc.test = CSEE.UMBC.TEST

